# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: TEST - Build and deploy to Azure penu-thewishlist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.23.0'

      - name: Build
        run: go build -v -o ${{env.DOTNET_ROOT}}/build/main ./cmd/main.go

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: thewishlist
          path: ${{env.DOTNET_ROOT}}/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: thewishlist
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_80AB6143B88644EEAB739EEEAF84781D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5422553DE5944AE39D6A0A9A890D9702 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22DC596C4A734012A424B80484B64946 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'penu-thewishlist'
          slot-name: 'Production'
          package: .
          